import Provider from '../components/Provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
  session: any,
}) {
  return (
      <html lang="pt-br">
        <body 
          style={{
            padding: 0,
            margin: 0,
            overflow: 'hidden',
          }}
        >
          <Provider>
            {children}
          </Provider>
        </body>
      </html>
  )
}
