export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body 
        style={{
          padding: 0,
          margin: 0,
          overflow: 'hidden',
        }}

      >
        {children}
      </body>
    </html>
  )
}
